import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
    return (
        <Html lang="en">
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta charSet="utf-8" />
                <meta name="theme-color" content="#4285f4" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="apple-touch-icon" href="/path/to/apple-touch-icon.png" />
            </Head>
            <body>
                <Main />
                <NextScript />
            </body>
        </Html>
    )
}