import { useRef } from "react";
import Header from '../components/Header.js';
import HomePage from '../components/HomePage.js'
import Works from "../components/Works.js";
import Slider from "../components/Slider";
import axios from 'axios'
import RatingPopUp from "../components/RatingPopUp.js";
import Head from "next/head"
export default function Home({ reviews, average_rating }) {
  const mainRef = useRef(null);
  const homeRef = useRef(null);
  const worksRef = useRef(null);
  return (
    <div className="overflow-x-hidden relative ">
      <Head>
        <title>Mohammed Abdulaziz</title>
        <meta name="description" content="Generated by create next app" />
        {/* <meta name="theme-color" content="#4285f4" /> */}
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/path/to/apple-touch-icon.png" />
      </Head>
      {/* <Slider /> */}
      <Header homeRef={homeRef} worksRef={worksRef} />
      <main ref={mainRef} className="bg-white_color overflow-hidden">
        <HomePage homeRef={homeRef} />
        <div ref={worksRef} className="h-[75px]"></div>
        <Works reviews={reviews} average_rating={average_rating} />
      </main>
    </div>
  )
}
export const getStaticProps = async () => {
  const res = await axios("http://localhost:3000/api/review");
  const reviews = res.data;
  const totalReviews = res.data.reduce((sum, current) => sum + current.stars, 0)
  const average_rating = totalReviews / res.data.length;

  return {
    props: {
      reviews,
      average_rating
    },
  }
}